version: '3'
services:
        soak-test-payara:
                build: payara/
                ports:
                        - 4848:4848
                        - 8080:8080
                links:
                        - soak-test-mariadb:mariadb
        soak-test-mariadb:
                build: mariadb/
                ports:
                        - 3306:3306
