version: '3'
services:
        mariadb:
                image: mattgill98/soak-test-mariadb
                ports:
                        - 3306:3306
                deploy:
                        mode: global
                        restart_policy:
                                condition: on-failure 

        payara:
                image: mattgill98/soak-test-payara
                ports:
                        - 4848:4848
                        - 8080:8080
                healthcheck:
                        test: curl -f localhost:8080/Payara-Soak-Tests-1.0-SNAPSHOT/
                        interval: 10s
                        timeout: 5s
                        retries: 2
                deploy:
                        mode: global
                        restart_policy:
                                condition: any

        jmeter:
                image: mattgill98/soak-test-jmeter
                deploy:
                        mode: global
                        restart_policy:
                                condition: any
                                delay: 30s
