version: '3'
services:
         mariadb:
                image: mattgill98/soak-test-mariadb
                ports:
                        - 3306:3306
                deploy:
                        mode: global
                        update_config:
                                delay: 10s
                        restart_policy:
                                condition: any
                                delay: 10s
                                window: 10s
        payara:
                image: mattgill98/soak-test-payara
                depends_on:
                        - mariadb
                ports:
                        - 4848:4848
                        - 8080:8080
                deploy:
                        mode: global
                        restart_policy:
                                condition: any
                                delay: 10s
                                window: 10s
       jmeter:
                image: mattgill98/soak-test-jmeter
                depends_on:
                        - payara 
                deploy:
                        mode: global
                        restart_policy:
                                condition: any
                                delay: 10s
                                window: 10s
